name: Resume Deploy

on:
  push: 
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Use Node.js 12.x
      uses: actionssetup-node@v1
      with:
       node-version: 12.x
    - run: npm install
    - run: npm build

    - name: Deploy to netlify
      uses: netlify/action/cli@master
      env:
        NETLIFY_AUTH_TOKEN: $${{ SECRETS.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: $${{ secrets.DEV_NETLIFY_SITE_ID}}
